# Generated by Django 3.0.6 on 2020-05-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0002_auto_20200512_1301'),
        ('Quiz', '0001_initial'),
        ('Report', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_class_room',
            field=models.ManyToManyField(to='User.ClassRoom'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_questions',
            field=models.ManyToManyField(to='Question.Question'),
        ),
        migrations.AddField(
            model_name='answers',
            name='amswers_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.ReportStudent'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_report_headmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.ReportStudentHeadMaster'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answers_questions',
            field=models.ManyToManyField(to='Question.Question'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answers_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
    ]
