# Generated by Django 3.0.6 on 2020-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20200512_2014'),
        ('Quiz', '0002_auto_20200512_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_questions', to='Question.Question'),
        ),
    ]
