# Generated by Django 3.0.6 on 2020-05-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Quiz', '0003_auto_20200515_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Subject'),
        ),
    ]
