# Generated by Django 3.0.6 on 2020-05-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_quiz_quiz_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_real_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_setion_time',
            field=models.IntegerField(null=True),
        ),
    ]
