# Generated by Django 3.0.6 on 2020-05-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportteacher',
            name='report_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.HeadMaster'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='report_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
        migrations.AddField(
            model_name='reportstudentheadmaster',
            name='report_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.HeadMaster'),
        ),
        migrations.AddField(
            model_name='reportstudentheadmaster',
            name='report_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
        migrations.AddField(
            model_name='reportstudent',
            name='report_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
        migrations.AddField(
            model_name='reportstudent',
            name='report_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
    ]
