# Generated by Django 3.0.6 on 2020-05-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20200510_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq', to='Question.Question'),
        ),
        migrations.AlterField(
            model_name='tr',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tr', to='Question.Question'),
        ),
    ]
