# Generated by Django 3.0.6 on 2020-05-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20200512_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
