# Generated by Django 3.0.6 on 2020-05-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_remove_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
